version: '3'
services:
  youtube_sharing_app_rails:
    container_name: youtube_sharing_app_rails
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./bin/docker_start.sh
    volumes:
      - bundle_path:/bundle
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_PORT: 3000
    env_file:
      - environments/docker_development.env
    links:
      - youtube_sharing_app_postgres:youtube_sharing_app_postgres
    depends_on:
      - youtube_sharing_app_postgres
    tty: true
    stdin_open: true

  youtube_sharing_app_postgres:
    container_name: youtube_sharing_app_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6.2.6
    command: redis-server
    restart: unless-stopped
    volumes:
      - redis:/var/lib/redis/data


  # sidekiq:
  #   links:
  #     - 'youtube_sharing_app_postgres:youtube_sharing_app_postgres'
  #     - 'redis:redis'
  #   depends_on:
  #     - 'youtube_sharing_app_postgres'
  #     - 'redis'
  #   build: .
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   volumes:
  #     - bundle_sidekiq_path:/bundle
  #     - .:/app
  #   env_file:
  #     - ./environments/docker_development.env

volumes:
  bundle_path:
  bundle_sidekiq_path:
  postgres_data:
  redis:
