# fly.toml app configuration file generated for sharing-videos-app on 2023-06-13T22:47:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "youtube-sharing-videos"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
